import React, { useState } from 'react';
import { Send } from 'lucide-react';

const Contact = () => {
  const [formData, setFormData] = useState({ name: '', email: '', message: '' });
  const [status, setStatus] = useState('');

  const handleSubmit = (e) => {
    e.preventDefault();
    // In a real implementation this would hit an API endpoint
    setStatus('Thank you for your message! We will get back to you shortly.');
    setFormData({ name: '', email: '', message: '' });
  };

  return (
    <div className="max-w-[800px] mx-auto px-4 py-16 w-full">
      <h1 className="text-3xl md:text-5xl font-extrabold text-white mb-8 border-b border-slate-700 pb-4">Contact Us</h1>
      
      <p className="mb-8 text-slate-300 leading-relaxed">
        Have questions, feedback, or need to report an issue? We'd love to hear from you. Please fill out the form below and our team will respond as soon as possible.
      </p>

      <form onSubmit={handleSubmit} className="bg-[#1e293b] p-6 md:p-8 rounded-2xl border border-slate-700/50 shadow-xl max-w-2xl">
        
        {status && (
          <div className="mb-6 p-4 bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 rounded-lg font-medium">
            {status}
          </div>
        )}

        <div className="mb-5">
          <label htmlFor="name" className="block text-slate-300 font-medium mb-2 text-sm">Your Name</label>
          <input 
            type="text" 
            id="name"
            required
            value={formData.name}
            onChange={(e) => setFormData({...formData, name: e.target.value})}
            className="w-full bg-[#0f1115] border border-slate-700 rounded-lg px-4 py-3 text-white placeholder:text-slate-600 focus:outline-none focus:border-[#10b981] transition-colors"
            placeholder="John Doe"
          />
        </div>

        <div className="mb-5">
          <label htmlFor="email" className="block text-slate-300 font-medium mb-2 text-sm">Your Email</label>
          <input 
            type="email" 
            id="email"
            required
            value={formData.email}
            onChange={(e) => setFormData({...formData, email: e.target.value})}
            className="w-full bg-[#0f1115] border border-slate-700 rounded-lg px-4 py-3 text-white placeholder:text-slate-600 focus:outline-none focus:border-[#10b981] transition-colors"
            placeholder="john@example.com"
          />
        </div>

        <div className="mb-6">
          <label htmlFor="message" className="block text-slate-300 font-medium mb-2 text-sm">Message</label>
          <textarea 
            id="message"
            required
            rows="5"
            value={formData.message}
            onChange={(e) => setFormData({...formData, message: e.target.value})}
            className="w-full bg-[#0f1115] border border-slate-700 rounded-lg px-4 py-3 text-white placeholder:text-slate-600 focus:outline-none focus:border-[#10b981] transition-colors resize-y"
            placeholder="How can we help you?"
          ></textarea>
        </div>

        <button 
          type="submit"
          className="w-full btn-green font-bold py-3.5 rounded-lg flex items-center justify-center gap-2"
        >
          Send Message <Send size={18} />
        </button>

      </form>
      
      <div className="mt-12 text-slate-400 text-sm">
        <p><strong>Note for DMCA / Copyright claims:</strong></p>
        <p className="mt-2">
          If you are filing a copyright claim, please clearly identify the exact URL generated by our service along with proof of ownership. As stated in our Disclaimer, Snapvio does not host any files.
        </p>
      </div>
    </div>
  );
};

export default Contact;
